training:
  seed: 2
  resume_from_checkpoint: null  # null to start from scratch
  inference_mode: mean  # mean, all, random_search, gradient_ascent
  inference_kwargs:
  batch_size: 128  # this has to be divisible by gradient_accumulation_steps * num_devices
  gradient_accumulation_steps: 1  # the higher the slower but the lower memory usage while keeping effective batch size constant
  total_num_steps: 5000
  log_every_n_steps: 100  # this has to respect dataset_size >= batch_size * log_every_n_steps
  eval_every_n_logs: 20  # null to disable eval
  save_checkpoint_every_n_logs: 10  # null to disable checkpointing
  learning_rate: 4e-4
  prior_kl_coeff: 1e-3
  pairwise_kl_coeff: null
  mixed_precision: False  # if True, it uses bfloat16 for activations (params stay in float32)
  online_data_augmentation: False
  task_generator:
    num_workers: 16
    num_pairs: 4
    class: STRUCT_PATTERN
    pattern: 3
    num_rows: 5
    num_cols: 5
  train_datasets:
  use_hf: True


eval:
  eval_datasets:
  test_datasets:
    - generator: STRUCT_PATTERN
      task_generator_kwargs:
        pattern: ${training.task_generator.pattern}
        num_rows: ${training.task_generator.num_rows}
        num_cols: ${training.task_generator.num_cols}
      name: struct_pattern_3
      num_pairs: 4
      length: 96
      batch_size: 96
      num_tasks_to_show: 4
    # - generator: PATTERN
    #   task_generator_kwargs:
    #     pattern_size: ${training.task_generator.pattern_size}
    #     num_rows: ${training.task_generator.num_rows}
    #     num_cols: ${training.task_generator.num_cols}
    #   name: generator_gradient_ascent_5
    #   num_pairs: 4
    #   length: 96
    #   batch_size: 96
    #   num_tasks_to_show: 32
    #   inference_mode: gradient_ascent
    #   inference_kwargs:
    #     num_steps: 10
    #     lr: 0.1
  json_datasets:


encoder_transformer:
  _target_:  models.utils.EncoderTransformerConfig
  max_rows: 5
  max_cols: 5
  num_layers: 2
  transformer_layer:
    _target_:  models.utils.TransformerLayerConfig
    num_heads: 6
    emb_dim_per_head: 12
    mlp_dim_factor: 4.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
  latent_dim: 32
  variational: True
  latent_projection_bias: False


decoder_transformer:
  _target_:  models.utils.DecoderTransformerConfig
  max_rows: 5
  max_cols: 5
  num_layers: 2
  transformer_layer:
    _target_:  models.utils.TransformerLayerConfig
    num_heads: 6
    emb_dim_per_head: 12
    mlp_dim_factor: 4.0
    dropout_rate: 0.0
    attention_dropout_rate: 0.0
